"""
API routes package.
"""

from app.api import (
    auth,
    tenants,
    suppliers,
    accommodations,
    contracts,
    trips,
    quotation,
    alerts,
    dashboard,
    formulas,
    services,
    dossiers,
    travel_themes,
    exchange_rates,
    trip_locations,
    country_templates,
    partner_agencies,
    distribution,
    import_circuit,
    contract_extraction,
    locations,
    cost_natures,
    conditions,
    trip_conditions,
)

__all__ = [
    "auth",
    "tenants",
    "suppliers",
    "accommodations",
    "contracts",
    "trips",
    "quotation",
    "alerts",
    "dashboard",
    "formulas",
    "services",
    "dossiers",
    "travel_themes",
    "exchange_rates",
    "trip_locations",
    "country_templates",
    "partner_agencies",
    "distribution",
    "import_circuit",
    "contract_extraction",
    "locations",
    "cost_natures",
    "conditions",
    "trip_conditions",
]
