"""Trip photos table for AI-generated and uploaded images.

Revision ID: 034_trip_photos
Revises: 033_content_cta_blocks
Create Date: 2025-02-08

Stores photos generated by Vertex AI (Imagen 3) for trip day-by-day descriptions.
Photos are organized by SEO nomenclature: Destination / Type / Attraction / seo-filename.avif
Includes optimized variants (AVIF, WebP), srcset data, and LQIP placeholders.
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID, JSONB


revision = '034_trip_photos'
down_revision = '033_content_cta_blocks'
branch_labels = None
depends_on = None


def upgrade():
    # ================================================================
    # Table: trip_photos
    # ================================================================
    op.create_table(
        'trip_photos',

        # Primary key (BigInteger auto-increment, same as TenantBase)
        sa.Column('id', sa.BigInteger, primary_key=True, autoincrement=True),

        # Tenant isolation
        sa.Column('tenant_id', UUID(as_uuid=True), sa.ForeignKey('tenants.id', ondelete='CASCADE'), nullable=False),

        # Trip relationship
        sa.Column('trip_id', sa.BigInteger, sa.ForeignKey('trips.id', ondelete='CASCADE'), nullable=False),

        # Day relationship (nullable for trip-level hero images)
        sa.Column('trip_day_id', sa.BigInteger, sa.ForeignKey('trip_days.id', ondelete='CASCADE'), nullable=True),

        # Day number (denormalized for convenience)
        sa.Column('day_number', sa.Integer, nullable=True),

        # ---- SEO Nomenclature ----
        # Path: media/{tenant}/{destination}/{attraction_type}/{attraction_slug}/{seo_filename}.avif
        sa.Column('destination', sa.String(100), nullable=True),         # "thailand"
        sa.Column('attraction_type', sa.String(50), nullable=True),      # "attraction", "destination", "activity"
        sa.Column('attraction_slug', sa.String(255), nullable=True),     # "wat-pho"
        sa.Column('seo_filename', sa.String(255), nullable=True),        # "temple-bouddha-couche-wat-pho-bangkok"

        # ---- Storage and URLs ----
        sa.Column('storage_path', sa.String(500), nullable=True),
        sa.Column('url', sa.String(1000), nullable=False),
        sa.Column('thumbnail_url', sa.String(1000), nullable=True),

        # ---- Optimized variants ----
        sa.Column('url_avif', sa.String(1000), nullable=True),
        sa.Column('url_webp', sa.String(1000), nullable=True),
        sa.Column('url_medium', sa.String(1000), nullable=True),         # 800px
        sa.Column('url_large', sa.String(1000), nullable=True),          # 1200px
        sa.Column('url_hero', sa.String(1000), nullable=True),           # 1920px
        sa.Column('srcset_json', JSONB, nullable=True),                  # Full srcset data
        sa.Column('lqip_data_url', sa.Text, nullable=True),             # Base64 blur placeholder

        # ---- Metadata ----
        sa.Column('original_filename', sa.String(255), nullable=True),
        sa.Column('file_size', sa.Integer, nullable=True),
        sa.Column('mime_type', sa.String(50), nullable=True),
        sa.Column('width', sa.Integer, nullable=True),
        sa.Column('height', sa.Integer, nullable=True),

        # ---- AI Generation tracking ----
        sa.Column('ai_prompt', sa.Text, nullable=True),
        sa.Column('ai_negative_prompt', sa.Text, nullable=True),
        sa.Column('ai_model', sa.String(100), nullable=True),
        sa.Column('ai_generated_at', sa.DateTime(timezone=True), nullable=True),

        # ---- Multi-language alt text and caption ----
        sa.Column('alt_text', sa.String(255), nullable=True),
        sa.Column('alt_text_json', JSONB, nullable=True),               # {"fr": "...", "en": "..."}
        sa.Column('caption_json', JSONB, nullable=True),                # {"fr": "...", "en": "..."}

        # ---- Flags ----
        sa.Column('is_hero', sa.Boolean, default=False, nullable=False, server_default='false'),
        sa.Column('is_ai_generated', sa.Boolean, default=False, nullable=False, server_default='false'),
        sa.Column('is_processed', sa.Boolean, default=False, nullable=False, server_default='false'),
        sa.Column('sort_order', sa.Integer, default=0, nullable=False, server_default='0'),

        # ---- Timestamps ----
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    )

    # ---- Indexes ----

    # Tenant isolation
    op.create_index('ix_trip_photos_tenant_id', 'trip_photos', ['tenant_id'])

    # Trip lookup
    op.create_index('ix_trip_photos_trip_id', 'trip_photos', ['trip_id'])

    # Day lookup
    op.create_index('ix_trip_photos_trip_day_id', 'trip_photos', ['trip_day_id'])

    # Composite: tenant + trip (most common query)
    op.create_index('ix_trip_photos_tenant_trip', 'trip_photos', ['tenant_id', 'trip_id'])

    # Composite: trip + day (for day-level queries)
    op.create_index('ix_trip_photos_trip_day', 'trip_photos', ['trip_id', 'trip_day_id'])

    # SEO: destination + type + slug (for deduplication and content reuse)
    op.create_index('ix_trip_photos_destination', 'trip_photos', ['destination', 'attraction_type', 'attraction_slug'])


def downgrade():
    # Drop indexes first
    op.drop_index('ix_trip_photos_destination')
    op.drop_index('ix_trip_photos_trip_day')
    op.drop_index('ix_trip_photos_tenant_trip')
    op.drop_index('ix_trip_photos_trip_day_id')
    op.drop_index('ix_trip_photos_trip_id')
    op.drop_index('ix_trip_photos_tenant_id')

    # Drop table
    op.drop_table('trip_photos')
