"""
AI Alert model - generated by the price controller.
"""

from decimal import Decimal
from typing import Optional, TYPE_CHECKING

from sqlalchemy import BigInteger, String, Text, DECIMAL, ForeignKey, Enum as SQLEnum
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import TenantBase

if TYPE_CHECKING:
    from app.models.trip import Trip
    from app.models.item import Item
    from app.models.contract import Contract
    from app.models.supplier import Supplier
    from app.models.user import User


class AIAlert(TenantBase):
    """
    An alert generated by the AI price controller.
    Tracks pricing anomalies, contract issues, and other concerns.
    """

    __tablename__ = "ai_alerts"

    # Alert type
    type: Mapped[str] = mapped_column(
        SQLEnum(
            "price_mismatch_contract_vs_db",
            "price_mismatch_db_vs_trip",
            "contract_expiring",
            "contract_expired",
            "missing_item",
            "season_mismatch",
            "allowance_anomaly",
            "stale_price",
            name="alert_type_enum"
        ),
        nullable=False,
    )

    # Severity
    severity: Mapped[str] = mapped_column(
        SQLEnum("critical", "important", "info", name="alert_severity_enum"),
        nullable=False,
    )

    # Context references (all optional)
    trip_id: Mapped[Optional[int]] = mapped_column(
        BigInteger,
        ForeignKey("trips.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
    )
    item_id: Mapped[Optional[int]] = mapped_column(
        BigInteger,
        ForeignKey("items.id", ondelete="CASCADE"),
        nullable=True,
    )
    contract_id: Mapped[Optional[int]] = mapped_column(
        BigInteger,
        ForeignKey("contracts.id", ondelete="CASCADE"),
        nullable=True,
    )
    supplier_id: Mapped[Optional[int]] = mapped_column(
        BigInteger,
        ForeignKey("suppliers.id", ondelete="CASCADE"),
        nullable=True,
    )

    # Price comparison
    expected_value: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    actual_value: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    price_difference: Mapped[Optional[Decimal]] = mapped_column(DECIMAL(12, 2), nullable=True)
    price_difference_pct: Mapped[Optional[Decimal]] = mapped_column(DECIMAL(5, 2), nullable=True)

    # Message
    message: Mapped[str] = mapped_column(Text, nullable=False)
    suggested_action: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Status
    status: Mapped[str] = mapped_column(
        SQLEnum("open", "acknowledged", "resolved", "dismissed", name="alert_status_enum"),
        default="open",
    )

    # Assignment
    assigned_to_id: Mapped[Optional[int]] = mapped_column(
        BigInteger,
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
    resolved_by_id: Mapped[Optional[int]] = mapped_column(
        BigInteger,
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )

    # Relationships
    trip: Mapped[Optional["Trip"]] = relationship("Trip")
    item: Mapped[Optional["Item"]] = relationship("Item")
    contract: Mapped[Optional["Contract"]] = relationship("Contract")
    supplier: Mapped[Optional["Supplier"]] = relationship("Supplier")
    assigned_to: Mapped[Optional["User"]] = relationship("User", foreign_keys=[assigned_to_id])
    resolved_by: Mapped[Optional["User"]] = relationship("User", foreign_keys=[resolved_by_id])

    def __repr__(self) -> str:
        return f"<AIAlert(id={self.id}, type='{self.type}', severity='{self.severity}')>"


# Import at end to avoid circular imports
from app.models.trip import Trip
from app.models.item import Item
from app.models.contract import Contract
from app.models.supplier import Supplier
from app.models.user import User
