"""
TripPhoto model - Photos for trip days.

Generated by Vertex AI (Imagen 3) or uploaded manually.
Stored in Supabase Storage with optimized variants (AVIF, WebP).
Organized by: Destination / Type / Attraction.
"""

import uuid
from typing import Optional, TYPE_CHECKING
from datetime import datetime

from sqlalchemy import (
    BigInteger, String, Boolean, Integer, ForeignKey, Text,
    DateTime, Index,
)
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.sql import func

from app.models.base import Base, TimestampMixin

if TYPE_CHECKING:
    from app.models.trip import Trip, TripDay


class TripPhoto(Base, TimestampMixin):
    """
    Photo associated with a trip day.

    Storage path follows SEO nomenclature:
    media/{destination}/{type}/{entity_slug}/{seo-filename}.avif

    Example:
    media/thailand/attraction/wat-pho/temple-bouddha-couche-wat-pho-bangkok.avif
    """

    __tablename__ = "trip_photos"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)

    # Tenant isolation
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # Trip relationship
    trip_id: Mapped[int] = mapped_column(
        BigInteger,
        ForeignKey("trips.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # Day relationship (nullable for trip-level hero images)
    trip_day_id: Mapped[Optional[int]] = mapped_column(
        BigInteger,
        ForeignKey("trip_days.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
    )

    # Day number (denormalized for convenience)
    day_number: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)

    # SEO nomenclature
    destination: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)  # "thailand"
    attraction_type: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)  # "attraction", "destination", "activity"
    attraction_slug: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)  # "wat-pho"
    seo_filename: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)  # "temple-bouddha-couche-wat-pho-bangkok"

    # Storage and URLs
    storage_path: Mapped[Optional[str]] = mapped_column(String(500), nullable=True)
    url: Mapped[str] = mapped_column(String(1000), nullable=False)
    thumbnail_url: Mapped[Optional[str]] = mapped_column(String(1000), nullable=True)

    # Optimized variants
    url_avif: Mapped[Optional[str]] = mapped_column(String(1000), nullable=True)
    url_webp: Mapped[Optional[str]] = mapped_column(String(1000), nullable=True)
    url_medium: Mapped[Optional[str]] = mapped_column(String(1000), nullable=True)  # 800px
    url_large: Mapped[Optional[str]] = mapped_column(String(1000), nullable=True)   # 1200px
    url_hero: Mapped[Optional[str]] = mapped_column(String(1000), nullable=True)    # 1920px
    srcset_json: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True)
    lqip_data_url: Mapped[Optional[str]] = mapped_column(Text, nullable=True)  # Base64 blur placeholder

    # Metadata
    original_filename: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    file_size: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    mime_type: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    width: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    height: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)

    # AI generation tracking
    ai_prompt: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    ai_negative_prompt: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    ai_model: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    ai_generated_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)

    # Multi-language alt text and caption
    alt_text: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    alt_text_json: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True)  # {"fr": "...", "en": "..."}
    caption_json: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True)

    # Flags
    is_hero: Mapped[bool] = mapped_column(Boolean, default=False)  # Hero banner for the day
    is_ai_generated: Mapped[bool] = mapped_column(Boolean, default=False)
    is_processed: Mapped[bool] = mapped_column(Boolean, default=False)
    sort_order: Mapped[int] = mapped_column(Integer, default=0)

    # Relationships
    trip: Mapped["Trip"] = relationship("Trip", back_populates="photos")
    trip_day: Mapped[Optional["TripDay"]] = relationship("TripDay", back_populates="photos")

    __table_args__ = (
        Index("ix_trip_photos_tenant_trip", "tenant_id", "trip_id"),
        Index("ix_trip_photos_trip_day", "trip_id", "trip_day_id"),
        Index("ix_trip_photos_destination", "destination", "attraction_type", "attraction_slug"),
    )

    def __repr__(self) -> str:
        return f"<TripPhoto(id={self.id}, trip_id={self.trip_id}, day={self.day_number}, seo={self.seo_filename})>"

    @property
    def storage_base_path(self) -> str:
        """Build the SEO storage path: media/{destination}/{type}/{slug}/"""
        parts = ["media"]
        if self.destination:
            parts.append(self.destination)
        if self.attraction_type:
            parts.append(self.attraction_type)
        if self.attraction_slug:
            parts.append(self.attraction_slug)
        return "/".join(parts)
